### ISSUE TITLE
Geophysics.jl

### ISSUE THREAD

**Issue by chakravala** [JuliaSpace/SatelliteToolboxAtmosphericModels.jl#1]
The [Geophysics.jl](https://github.com/chakravala/Geophysics.jl) package provides a finely tuned standard atmosphere for the aviation regime; it does not currently include a finely tuned model for the satellite regime, although it has been designed with such extensions in mind.

If you were not intending to contribute to the `Geophysics` package, seeing this repository reminds me to extend this myself then.

**Comment by ronisbr** [comment]
Hi @chakravala !

I did not know about Geophysics.jl. It seems an awesome package! Congratulations!

I will be glad to port the models here to Geophysics.jl in the future. However, it can take a significant amount of time because I am in the middle of a complete revamp of SatelliteToolbox.jl, splitting the package into smaller modules.

However, if you want, feel free to copy the models :) The most important for satellites are the NRLMSISE-00, JR1971 and JB2008. In those cases, you will need some space indices that you can obtain with the package [SpaceIndices.jl](https://github.com/JuliaSpace/SpaceIndices.jl).

**Comment by ronisbr** [comment]
Oh! There is a problem. I would not be able to use your package if the license is AGPL. The SatelliteToolbox ecosystem is used for many tasks in the National Institute for Space Research. Hence, there are some approved licenses since we must be able to perform modifications without disclosing the source code. Would you mind changing the package license to MIT?

**Comment by chakravala** [comment]
It's potentially possible for me to switch that package to MIT, is the National Institute for Space Research willing to fund the maintenance of the package? I'm glad you are interested in it, if you're really serious about using it then I will consider the possibility of changing the license. Just a 2 comment discussion is not enough to convince me to change a license, but if you're somehow serious about it we can discuss it further.

**Comment by ronisbr** [comment]
> is the National Institute for Space Research willing to fund the maintenance of the package?

If you are Brazilian and submit a solid project that catch the interest, maybe...

> Just a 2 comment discussion is not enough to convince me to change a license, but if you're somehow serious about it we can discuss it further.

Ok, but I cannot start to contribute to a package that the license does not allow closed-source applications with modifications. Feel free to ping me if you change your mind.

**Comment by chakravala** [comment]
I will certainly consider changing the license if you are serious about using `Geophysics`; however, you have not given me much confidence that you intend to use the package, so changing the license is not worth it unless you demonstrate that you're more serious about contributing to it.

Also,  some of your models here might be too complicated for my package. In `Geophysics` the goal is to have a quickly loading package with fast and simple models. I haven't tested yours yet, but it looks more complicated.
